---
- hosts: serverSql
  become: true

  tasks:
  - name: Install mariadb + dépendances
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - mariadb-server
      - mariadb-client
      - python3-pip
      - python3-dev
      - python3-mysqldb