---

all:
  children:
    webserver:

      hosts:
#          10.49.34.144:
#             ansible_user: tim1
           10.49.33.163:
             ansible_user: tim2

    syslog:
      hosts:
          10.49.33.157:
            ansible_user: tim3
