---
- hosts: syslog
  become: true
  tasks:
    - name: install rsyslog
      apt:
          name: rsyslog
          update_cache: yes
          state: present

    - name: Activer le UDP
      ansible.builtin.lineinfile:
          path: /etc/rsyslog.conf
          regexp: '^(.*)module\(load="imudp"\)$'
          line: 'module(load="imudp")'

    - name: Activer le port UDP
      ansible.builtin.lineinfile:
           path: /etc/rsyslog.conf
           regexp: '^(.*)input\(type="imudp" port="514"\)$'
           line: 'input(type="imudp" port="514")'

    - name: Activer le TCP
      ansible.builtin.lineinfile:
            path: /etc/rsyslog.conf
            regexp: '^(.*)module\(load="imtcp"\)$'
            line: 'module(load="imtcp")'

    - name: Activer le port TCP
      ansible.builtin.lineinfile:
             path: /etc/rsyslog.conf
             regexp: '^(.*)input\(type="imtcp" port="514"\)$'
             line: 'input(type="imtcp" port="10514")'

    - name: Redémarrer le service Syslog
      service:
            name: rsyslog
            state: restarted

- hosts: webserver
  become: true
  tasks:
     - name: install rsyslog
       apt:
           name: rsyslog
           update_cache: yes
           state: present

     - name: Redémarrer le service Syslog
       service:
           name: rsyslog
           state: restarted

     - name: Ajout du serveur dans le fichier de configuration
       ansible.builtin.lineinfile:
             path: /etc/rsyslog.conf
             line: '*.* @10.49.33.157:514'


