---
- hosts: serverSql
  become: true

  tasks:

  - name: Restart MariaDB 10.3
    service: name=mysql state=restarted

  - name: Create MariaDB Directories
    file: path=/data/MariaDB state=directory owner=mysql group=mysql recurse=yes
    with_items:
      - db
      - log

  - name: Count files in /data/db
    find:
      path=/data/db
      patterns='\*'
    register: db_files

  - name: Run mysql_install_db only if /data/db is empty
    command: mysql_install_db --datadir=/data/db
    when: db_files.matched|int == 0

  - name: Write new configuration file
    template:
      src: ...
      dest: /etc/mysql/my.cnf
      owner: mysql
      group: mysql
      mode: '0600'
      backup: yes

  - name: Start MariaDB
    service:
      name=mysql
      state=started

  - name: Is root password set?
    command: mysql -u root --execute "SELECT NOW()"
    register: is_root_password_set
    ignore_errors: yes

  - name: Generate mysql root password
    shell: tr -d -c "a-zA-Z0-9" \< /dev/urandom | head -c 10
    register: mysql_root_password
    when: is_root_password_set.rc == 0

  - name: Create myapp database
    mysql_db:
      name: myapp
      login_user: root
      login_password: password
      login_host: localhost
      state: present
    when: is_root_password_set.rc == 0

  - name: Create user for myapp db
    mysql_user:
      name: myapp_rw
      password: password
      priv: myapp.*:SELECT,INSERT,UPDATE,DELETE
      login_user:
      root login_password: password
      state: present
    when: is_root_password_set.rc == 0