---
- hosts: webserver
  become: true
  pre_tasks:
    - name: Creates directory
      file:
        path: /home/glpi/public_html
        state: directory
  roles:
    - role: gsquad934.glpi



