---
- hosts: webserver
  become: true
  tasks:
    - name: Installation heartbeat
      apt: name=heartbeat update_cache=yes state=latest
    - name: Remplacer du contenu fichier
          lineinfile:
            dest: /etc/hearbeat/ha.cf
            insertafter: BOF
            line: logfile /var/log/ha-log
                  logfacility local0
                  keepalive 2
                  deadtime 10
                  bcast eth0
                  node nom_serveur1 nom_serveur2
                  auto_failback no
                  respawn hacluster /usr/lib/heartbeat/ipfail
                  apiauth ipfail gid=haclient uid=hacluster