---
- hosts: serverSql
  become: true

  vars:
    pg_version: postgresql-12.7

  tasks:
  - name: "Find out if PostgreSQL is initialized"
    ansible.builtin.stat:
      path: /etc/postgresql/12/main/pg_hba.conf
    register: postgres_data

  - name: "Initialize PostgreSQL"
    shell: postgresql-setup initdb
    when: not postgres_data.stat.exists

  - name: "Start and enable services"
    service: name=postgresql.service state=started enabled=yes
    with_items:
      - postgresql

  handlers:
  - name: restart postgres
    service: name=postgresql state=restarted