---
- hosts: serverSql2
  become: true

  tasks:
  - name: Create user with password, all database privileges and 'WITH GRANT OPTION' in db1 and db2
    community.mysql.mysql_user:
      state: present
      name: ansibleuser
      password: password
      priv:
        'db1.*': 'ALL,GRANT'
        'db2.*': 'ALL,GRANT'

#    - name: Write new configuration file
#      template:
#        src: ../Conf_Files_BDD/my.cnf
#        dest: /etc/mysql/my.cnf
#        owner: root
#        group: root
#        mode: '0644'
#        backup: yes

  #- name: Create myapp database
  #  mysql_db:
  #    name: myapp
  #    login_user: root
  #    login_password: password
  #    login_host: localhost
  #    state: present
#    when: is_root_password_set.rc == 0

#  - name: Generate myapp\_rw password
#    shell: tr -d -c "a-zA-Z0-9" < /dev/urandom | head -c 10
#    register: mysql_myapp_rw_password
#    when: is_root_password_set.rc == 0

#  - name: Create user for myapp db
#    mysql_user:
#      name: myapp_rw
#      password: password
#      priv: myapp.*:SELECT,INSERT,UPDATE,DELETE
#      login_user:
#      root login_password: password
#      state: present
#    when: is_root_password_set.rc == 0