---
- hosts: serverSql
  become: true

  tasks:
  - name: Install mariadb + dépendances
     apt: name={{item}} state=latest update_cache=yes
    with_items:
      - mariadb-server
      - mariadb-client
      - python3-pip
      - python3-dev
      - python3-mysqldb

  - name: Redémarrage de MariaDB
    service: name=mysql state=restarted

  - name: Création des répértoires de MariaDB
    file: path=/data/MariaDB state=directory owner=mysql group=mysql recurse=yes
    with_items:
      - db
      - log

  - name: Liste des fichiers sous /data/db
    find:
      path=/data/db
      patterns='\*'
    register: db_files

  - name: Démarre mysql_install_db dans le cas où /data/db est vide | Initialise MariaDB
    command: mysql_install_db --datadir=/data/db
    when: db_files.matched|int == 0

#  - name: Modification du fichier de configuration
#    template:
#      src: ./BDD/Conf_Files_BDD/my.cnf
#      dest: /etc/mysql/my.cnf
#      owner: mysql
#      group: mysql
#      mode: '0600'
#      backup: yes

  - name: Démarre MariaDB
    service:
      name=mysql
      state=started

  - name: Vérrifie et enregiste si l'utilisateur root de mariadb a un mdp
    command: mysql -u root --execute "SELECT NOW()"
    register: is_root_password_set
    ignore_errors: yes

  - name: Genère un mdp mysql pour l'utilisateur root
    shell: tr -d -c "a-zA-Z0-9" \< /dev/urandom | head -c 10
    register: mysql_root_password
    when: is_root_password_set.rc == 0

  - name: Crée la bdd "myapp"
    mysql_db:
      name: myapp
      login_user: root
      login_password: password
      login_host: localhost
      state: present

#  - name: Crée un utilisateur pour accéder à la bdd
#    mysql_user:
#      name: ansibleuser
#      password: password
#      priv: myapp.*:SELECT,INSERT,UPDATE,DELETE
#      login_user: ansibleuser
#      root login_password: password
#      state: present